name: All Examples Build Verification

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  examples-build-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Hello World
        run: |
          pushd hello-world
          chmod +x gradlew
          ./gradlew compileKotlin
          popd
